config/routes.rb
Rails.application.routes.draw do
  root "static#welcome"
  resources :tasks
  resources :buckets
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bucket.rb
class Bucket < ApplicationRecord
    has_many :tasks

    def self.get_by_status(status)
        self.all.select do |bucket|
            bucket.status == status
        end
    end

    def update_status
        if self.tasks == []
            self.status = "Empty"
        elsif self.tasks.any?{|task| task.status == "Pending"}
            self.status = "Pending"
        else
            self.status = "Completed"
        end
        self.save
    end

    def tasks_by_status(status)
        self.tasks.select do |task|
            task.status == status
        end
    end
end

app/models/task.rb
class Task < ApplicationRecord
  belongs_to :bucket

  def self.get_by_status(status)
    self.all.select do |task|
        task.status == status
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/buckets_controller.rb
class BucketsController < ApplicationController
    def index
        @empty_buckets = Bucket.get_by_status("Empty")
        @pending_buckets = Bucket.get_by_status("Pending")
        @completed_buckets = Bucket.get_by_status("Completed")
    end

    def new
        @bucket = Bucket.new
    end

    def create
        @bucket = Bucket.create(post_params(:name, :description))
        @bucket.status = "Empty"
        @bucket.save
        redirect_to bucket_path(@bucket)
    end

    def show
        @bucket = Bucket.find(params[:id])
    end

    def edit
        @bucket = Bucket.find(params[:id])
    end

    def update
        @bucket = Bucket.find(params[:id])
        @bucket.update(post_params(:name, :description))
        @bucket.update_status
        redirect_to bucket_path(@bucket)
    end

    def destroy
        @bucket = Bucket.find(params[:id]).destroy
        redirect_to buckets_path
    end

    private
    def post_params(*args)
        params.require(:bucket).permit(*args)
    end
end

app/controllers/static_controller.rb
class StaticController < ApplicationController
    def welcome
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
    def index
        @pending_tasks = Task.get_by_status("Pending")
        @completed_tasks = Task.get_by_status("Completed")
    end

    def new
        @task = Task.new
    end

    def create
        @task = Task.create(post_params(:name, :description, :bucket_id))
        @task.status = "Pending"
        @task.save
        @task.bucket.update_status
        redirect_to task_path(@task)
    end

    def show
        @task = Task.find(params[:id])
    end

    def edit
        @task = Task.find(params[:id])
    end

    def update
        @task = Task.find(params[:id])
        @task.update(post_params(:name, :description, :status, :bucket_id))
        @bucket = @task.bucket.update_status
        redirect_to task_path(@task)
    end

    def destroy
        @task = Task.find(params[:id]).destroy
        redirect_to tasks_path
    end

    private
    def post_params(*args)
        params.require(:task).permit(*args)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/buckets_helper.rb
module BucketsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/buckets/edit.html.erb
<h1><%= "EDIT: " + @bucket.name %></h1>
<%= form_for(@bucket) do |f| %>
    <%= f.label :name%><br>
    <%= f.text_field :name%><br>
    <br><%= f.label :description%><br>
    <%= f.text_area :description%><br>
    <br><%= f.submit %><br>
<% end %>
<br><%= button_to "Delete Bucket", @bucket, :method => :delete, data: {confirm: 'Are you sure?'} %>

app/views/buckets/index.html.erb
<h1>BUCKETS LIST</h1>
<%= button_to "Create Bucket", new_bucket_path, method: :get %>
<h3>Empty Buckets</h3>
<ul>
<% @empty_buckets.each do |bucket| %>
    <li><%= link_to bucket.name, bucket_path(bucket) %></li>
<% end %>
</ul>
<h3>Pending Buckets</h3>
<ul>
<% @pending_buckets.each do |bucket| %>
    <li><%= link_to bucket.name, bucket_path(bucket) %></li>
<% end %>
</ul>
<h3>Completed Buckets</h3>
<ul>
<% @completed_buckets.each do |bucket| %>
    <li><%= link_to bucket.name, bucket_path(bucket) %></li>
<% end %>
</ul>

app/views/buckets/new.html.erb
<h1>CREATE NEW BUCKET</h1>
<%= form_for(@bucket) do |f| %>
    <%= f.label :name%><br>
    <%= f.text_field :name%><br>
    <br><%= f.label :description%><br>
    <%= f.text_area :description%><br>
    <br><%= f.submit %>
<% end %>

app/views/buckets/show.html.erb
<h1><%= @bucket.name %></h1>
<p><%= @bucket.description %></p>
<h3>Pending Tasks</h3>
<ul>
    <% @bucket.tasks_by_status("Pending").each do |task| %>
        <li><%= link_to task.name, task_path(task) %></li>
    <% end %>
</ul>
<h3>Completed Tasks</h3>
<ul>
    <% @bucket.tasks_by_status("Completed").each do |task| %>
        <li><%= link_to task.name, task_path(task) %></li>
    <% end %>
</ul>
<%= button_to "Edit Bucket", edit_bucket_path(@bucket), method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    -->
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <!-- jQuery library -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <!-- Latest compiled JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  </head>

  <body style="margin: 4em">
    <%= link_to "All Buckets", buckets_path%>
    <%= link_to "All Tasks", tasks_path%>
    <%= yield %>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1><%= "EDIT: " + @task.name %></h1>
<%= form_for(@task) do |f| %>
    <%= f.label :name%><br>
    <%= f.text_field :name%><br>
    <br><%= f.label :description%><br>
    <%= f.text_area :description%><br>
    <br><%= f.label "Bucket"%>
    <%= f.collection_select :bucket_id, Bucket.order(:name),:id, :name %><br>
    <br><%= f.check_box :status, {}, "Completed", "Pending" %> Completed?<br>
    <br><%= f.submit %><br>
<% end %>
<br><%= button_to "Delete Task", @task, :method => :delete, data: {confirm: 'Are you sure?'} %>

app/views/tasks/index.html.erb
<h1>TASKS LIST</h1>
<%= button_to "Create Task", new_task_path, method: :get %>
<h3>Pending Tasks</h3>
<ul>
<% @pending_tasks.each do |task| %>
    <li><%= link_to task.name, task_path(task) %></li>
<% end %>
</ul>
<h3>Completed Tasks</h3>
<ul>
<% @completed_tasks.each do |task| %>
    <li><%= link_to task.name, task_path(task) %></li>
<% end %>
</ul>

app/views/tasks/new.html.erb
<h1>CREATE NEW TASK</h1>
<%= form_for(@task) do |f| %>
    <%= f.label :name%><br>
    <%= f.text_field :name%><br>
    <br><%= f.label :description%><br>
    <%= f.text_area :description%><br>
    <br><%= f.label "Bucket"%>
    <%= f.collection_select :bucket_id, Bucket.order(:name),:id, :name %><br>
    <br><%= f.submit %>
<% end %>

app/views/tasks/show.html.erb
<h1><%= @task.name %></h1>
<p><%= @task.description %></p>
<h6><%= @task.status %></h6>
<%= button_to "Edit task", edit_task_path(@task), method: :get %>